---

- set_fact:
    processed_volumes: '{{ volumes | operator_storage(meta.namespace) }}'
    has_route: "{{ ('route.openshift.io' in lookup('k8s', cluster_info='api_groups')) | bool }}"

- name: Create required resources for storage
  k8s:
    namespace: '{{ meta.namespace }}'
    definition: '{{ item }}'
  with_items: '{{ processed_volumes.definitions }}'

- name: Create Kubernetes deployment
  k8s:
    state: present
    namespace: '{{ meta.namespace }}'
    definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml }}"
  vars:
    volume_specs: '{{ processed_volumes.volumes }}'
    volume_mounts: '{{ processed_volumes.volume_mounts }}'

- name: Create Kubernetes service
  k8s:
    state: present
    namespace: '{{ meta.namespace }}'
    definition: "{{ lookup('template', 'service.yaml.j2') | from_yaml }}"

- name: Create OpenShift route
  k8s:
    state: present
    namespace: '{{ meta.namespace }}'
    definition: '{{ lookup("template", "route.yaml.j2") | from_yaml }}'
  when: has_route

- include_tasks: status.yml
  when: _apps_fabianism_us_jellyfin is defined
