---

- set_fact:
    processed_volumes: '{{ volumes | operator_storage(meta.namespace) }}'

- name: Create required resources for storage
  k8s:
    definition: '{{ item  }}'
  with_items: '{{ processed_volumes.definitions }}'

- name: Create Kubernetes deployment
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.yaml.j2') | from_yaml }}"
  vars:
    volumes: '{{ processed_volumes.volumes }}'
    volume_mounts: '{{ processed_volumes.volume_mounts }}'

- name: Create Kubernetes resources for Jellyfin
  k8s:
    state: present
    definition: '{{ lookup("file", item) | from_yaml }}'
  with_items:
  - service.yaml

- name: Create OpenShift route
  k8s:
    state: present
    definition: '{{ lookup("template", "route.yaml.j2") | from_yaml }}'
  when: "'route.openshift.io' in lookup('k8s', cluster_info='api_groups')"
