apiVersion: apps.fabianism.us/v1alpha1
kind: Jellyfin
metadata:
  name: example-jellyfin
spec:
  image: docker.io/jellyfin/jellyfin:latest
  volumes:
    config:
      type: EmptyDir
      readOnly: no
    media:
      type: EmptyDir
      readOnly: yes
      mountPath: /data/media
