---

- name: Verify
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
  - name: Output url
    debug: var={{ url }}

  - name: Wait two minutes to confirm URL is reachable
    uri:
      url: '{{ url }}'
      status_code:
      - 200
    retries: 24
    delay: 5
    register: result
    until: not (result is failed)
