---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    meta:
      name: example-jellyfin
      namespace: '{{ namespace }}'
    node_port: 30001
  tasks:
  - include_role:
      name: jellyfin

  - name: Wait for Deployment to finish
    debug: var=deploy.status
    until: deploy and deploy.status and deploy.status.replicas == deploy.status.get("availableReplicas", 0)
    retries: 12
    delay: 10
    vars:
      deploy: '{{ lookup("k8s",
        kind="Deployment",
        api_version="apps/v1",
        namespace=namespace,
        resource_name="jellyfin"
      )}}'

- import_playbook: '{{ playbook_dir }}/asserts.yml'
  vars:
    url: "http://{{ q('k8s',
      api_version='v1',
      kind='Pod',
      namespace=meta.namespace,
      label_selector='app=jellyfin'
    ).0.status.hostIP }}:{{ node_port }}"
    meta:
      name: example-jellyfin
      namespace: '{{ namespace }}'
    node_port: 30001
